# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jesse/CS2620/DE4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jesse/CS2620/DE4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jesse/CS2620/DE4/CMakeFiles /home/jesse/CS2620/DE4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jesse/CS2620/DE4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proto_files

# Build rule for target.
proto_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proto_files
.PHONY : proto_files

# fast build rule for target.
proto_files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto_files.dir/build.make CMakeFiles/proto_files.dir/build
.PHONY : proto_files/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named test_chat

# Build rule for target.
test_chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_chat
.PHONY : test_chat

# fast build rule for target.
test_chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/build
.PHONY : test_chat/fast

chat.grpc.pb.o: chat.grpc.pb.cc.o
.PHONY : chat.grpc.pb.o

# target to build an object file
chat.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/chat.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/chat.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/chat.grpc.pb.cc.o
.PHONY : chat.grpc.pb.cc.o

chat.grpc.pb.i: chat.grpc.pb.cc.i
.PHONY : chat.grpc.pb.i

# target to preprocess a source file
chat.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/chat.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/chat.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/chat.grpc.pb.cc.i
.PHONY : chat.grpc.pb.cc.i

chat.grpc.pb.s: chat.grpc.pb.cc.s
.PHONY : chat.grpc.pb.s

# target to generate assembly for a file
chat.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/chat.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/chat.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/chat.grpc.pb.cc.s
.PHONY : chat.grpc.pb.cc.s

chat.pb.o: chat.pb.cc.o
.PHONY : chat.pb.o

# target to build an object file
chat.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/chat.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/chat.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/chat.pb.cc.o
.PHONY : chat.pb.cc.o

chat.pb.i: chat.pb.cc.i
.PHONY : chat.pb.i

# target to preprocess a source file
chat.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/chat.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/chat.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/chat.pb.cc.i
.PHONY : chat.pb.cc.i

chat.pb.s: chat.pb.cc.s
.PHONY : chat.pb.s

# target to generate assembly for a file
chat.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/chat.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/chat.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/chat.pb.cc.s
.PHONY : chat.pb.cc.s

client-grpc-new.o: client-grpc-new.cpp.o
.PHONY : client-grpc-new.o

# target to build an object file
client-grpc-new.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client-grpc-new.cpp.o
.PHONY : client-grpc-new.cpp.o

client-grpc-new.i: client-grpc-new.cpp.i
.PHONY : client-grpc-new.i

# target to preprocess a source file
client-grpc-new.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client-grpc-new.cpp.i
.PHONY : client-grpc-new.cpp.i

client-grpc-new.s: client-grpc-new.cpp.s
.PHONY : client-grpc-new.s

# target to generate assembly for a file
client-grpc-new.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client-grpc-new.cpp.s
.PHONY : client-grpc-new.cpp.s

server-grpc-new.o: server-grpc-new.cpp.o
.PHONY : server-grpc-new.o

# target to build an object file
server-grpc-new.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server-grpc-new.cpp.o
.PHONY : server-grpc-new.cpp.o

server-grpc-new.i: server-grpc-new.cpp.i
.PHONY : server-grpc-new.i

# target to preprocess a source file
server-grpc-new.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server-grpc-new.cpp.i
.PHONY : server-grpc-new.cpp.i

server-grpc-new.s: server-grpc-new.cpp.s
.PHONY : server-grpc-new.s

# target to generate assembly for a file
server-grpc-new.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server-grpc-new.cpp.s
.PHONY : server-grpc-new.cpp.s

test_chat.o: test_chat.cpp.o
.PHONY : test_chat.o

# target to build an object file
test_chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/test_chat.cpp.o
.PHONY : test_chat.cpp.o

test_chat.i: test_chat.cpp.i
.PHONY : test_chat.i

# target to preprocess a source file
test_chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/test_chat.cpp.i
.PHONY : test_chat.cpp.i

test_chat.s: test_chat.cpp.s
.PHONY : test_chat.s

# target to generate assembly for a file
test_chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/test_chat.cpp.s
.PHONY : test_chat.cpp.s

user_auth/user_auth.o: user_auth/user_auth.cpp.o
.PHONY : user_auth/user_auth.o

# target to build an object file
user_auth/user_auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/user_auth/user_auth.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/user_auth/user_auth.cpp.o
.PHONY : user_auth/user_auth.cpp.o

user_auth/user_auth.i: user_auth/user_auth.cpp.i
.PHONY : user_auth/user_auth.i

# target to preprocess a source file
user_auth/user_auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/user_auth/user_auth.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/user_auth/user_auth.cpp.i
.PHONY : user_auth/user_auth.cpp.i

user_auth/user_auth.s: user_auth/user_auth.cpp.s
.PHONY : user_auth/user_auth.s

# target to generate assembly for a file
user_auth/user_auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/user_auth/user_auth.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/user_auth/user_auth.cpp.s
.PHONY : user_auth/user_auth.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... proto_files"
	@echo "... client"
	@echo "... server"
	@echo "... test_chat"
	@echo "... chat.grpc.pb.o"
	@echo "... chat.grpc.pb.i"
	@echo "... chat.grpc.pb.s"
	@echo "... chat.pb.o"
	@echo "... chat.pb.i"
	@echo "... chat.pb.s"
	@echo "... client-grpc-new.o"
	@echo "... client-grpc-new.i"
	@echo "... client-grpc-new.s"
	@echo "... server-grpc-new.o"
	@echo "... server-grpc-new.i"
	@echo "... server-grpc-new.s"
	@echo "... test_chat.o"
	@echo "... test_chat.i"
	@echo "... test_chat.s"
	@echo "... user_auth/user_auth.o"
	@echo "... user_auth/user_auth.i"
	@echo "... user_auth/user_auth.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

